- shell:
      - [git pull, Update repository]
      - [git submodule update --init --recursive, Update submodules]

- clean: ["~"]

- defaults:
      link:
          create: true
          relink: true

- link:
      ~/.bash_profile: ./shell/bash/.bash_profile
      ~/.bashrc: ./shell/bash/.bashrc

- shell:
      - [bash os/config.sh, Configure OS]
      - [bash shell/config.sh, Configure shell]
