- clean: ["~"]

- defaults:
    link:
      create: true
      force: true
      relink: true

- link:
    ~/.bash_profile: ./lib/shell/config/.bash_profile
    ~/.bashrc: ./lib/shell/config/.bashrc
    ~/.config/starship.toml: ./lib/shell/config/starship.toml
    ~/.vim/autoload/plug.vim: ./packages/vim-plug/plug.vim
    ~/.vimrc: ./lib/shell/config/.vimrc
    ~/.tmux.conf: ./lib/shell/config/.tmux.conf

- shell:
    - description: Configure OS
      command: bash lib/os/config.sh
      stdin: true
      stdout: true
      stderr: true
    - description: Configure shell
      command: bash lib/shell/config.sh
      stdin: true
      stdout: true
      stderr: true
