- shell:
      - [git pull, Update repository]
      - [git submodule update --init --recursive, Update submodules]

- clean: ["~"]

- defaults:
      link:
          create: true
          relink: true

- link:
      ~/.bash_profile: ./shell/bash/.bash_profile
      ~/.bashrc: ./shell/bash/.bashrc

- shell:
      - description: Configure OS
        command: bash os/config.sh
        stdin: true
        stdout: true
        stderr: true
      - description: Configure shell
        command: bash shell/config.sh
        stdin: true
        stdout: true
        stderr: true
