- clean: ["~"]

- defaults:
          link:
                  create: true
                  force: true
                  relink: true

- link:
          ~/.bash_profile: ./config/.bash_profile
          ~/.bashrc: ./config/.bashrc
          ~/.config/starship.toml: ./config/starship.toml
          ~/.vim/autoload/plug.vim: ./lib/vim-plug/plug.vim
          ~/.vimrc: ./config/.vimrc
          ~/.tmux.conf: ./config/.tmux.conf

- shell:
          - description: Configure OS
            command: bash os/config.sh
            stdin: true
            stdout: true
            stderr: true
          - description: Configure shell
            command: bash shell/config.sh
            stdin: true
            stdout: true
            stderr: true
